server:
  port: 7002
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.pacifique: DEBUG
spring:
  application:
    name: recommendation-service

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
