server:
  port: 7001

spring:
    application:
      name: product-service

logging:
  level:
    root: INFO
    com.pacifique: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8080