spring.application.name: eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 5000

management.endpoints.web.exposure.include:  "*"
