
spring:
  application:
    name: review-service
server:
  port: 7003
  error:
    include-message: always
logging:
  level:
    root: INFO
    com.pacifique: DEBUG


---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
